### ISSUE TITLE
Nested anonymous structs in every position

### ISSUE THREAD

**Issue by exellian** [oooutlk/structx#4]
With the release of version 0.1.9 nested anonymous structs are now initially supported. But there are still problems with nested anonymous structs in every position. E.g. when you wrap a nested anonymous struct in a Vec type then you still run into problems with a "cannot find type error":
```rust
Structx!{
    items: Vec<T>,
    test: usize,
    products: Vec<Structx!{ name: T1 }> // Using nested anonymous struct as generic parameter to a Vec-type
};
```

**Comment by exellian** [comment]
I will do this one and create a merge request.

**Comment by oooutlk** [comment]
Emmm... I didn't notice these complex cases. Need a solid solution. It would be nice if you can send pr, since I got busy these days.

**Comment by exellian** [comment]
Sure i'm already implemented a solution, I'm currently writing tests

**Comment by exellian** [comment]
Here it is!: https://github.com/oooutlk/structx/pull/5
I did 2 things: 
- Added support for scanning through syn::Type and syn::Pat for field members to collect all anonymous structs
- Bumped up version of syn to 2.0

I would recommend that you check and review all the changes before merging it.

P.S: In the future you could consider also adding support for nested anonymous structs in const generics and range expressions, because currently this is the only thing i didn't implement yet. But for this to work you would have pattern match against every expression-subtype, so it is a little bit complicated.

**Comment by oooutlk** [comment]
PR has been merged, and I ran `cargo fmt` on a published crate for the first time. See https://github.com/oooutlk/structx/pull/5#issuecomment-1551322072
