### ISSUE TITLE
Collector design + Parsing design

### ISSUE THREAD

**Issue by exellian** [oooutlk/structx#6]
So in syn there exist multiple different ways to parse a struct in different positions:
- PatStruct (https://docs.rs/syn/latest/syn/struct.PatStruct.html): a struct used in a pattern position, e.g: in pattern matching, if-blocks, match-blocks, etc...
- ExprStruct (https://docs.rs/syn/latest/syn/struct.ExprStruct.html): a struct used in an expr position, e.g: in an assignment:
```rust 
let x = MyStruct { name: 0, x: "" }; 
```
- ItemStruct (https://docs.rs/syn/latest/syn/struct.ItemStruct.html#): a struct type definition, e.g:
```rust
struct MyStruct {
    field: usize,
    nested: MyOtherStruct,
}
```
- PatTupleStruct (https://docs.rs/syn/latest/syn/struct.PatTupleStruct.html#): a tuple struct in a pattern position. We should not support these because they have no field names.
- DataStruct (https://docs.rs/syn/latest/syn/struct.DataStruct.html#): i think we can ignore them

The problem is that currently we simply parse the inner of every structx!/Structx!/args! macro as a PatStruct. This leads to problems when just using the Structx! macro alone. Because the parsing will simply fail and the user will get a "type not found error". 

We should discuss how to rework this. I can think of 3 solutions:
1. introducing a new macro like structxp! which only parses PatStruct, structx! will then parse only ExprStruct and Structx! will parse ItemStruct
2. reducing all cases to one macro structx! and try to parse every case in some order. So e.g: first try parsing against ItemStruct, then ExprStruct, then PatStruct
3. Leaving it as it is and structx! now tries to parse ExprStruct and if it fails then it tries to parse PatStruct

**Comment by oooutlk** [comment]
I think utilizing two macros(`structx` vs `Structx`) is proper. The uppercase “S” follows the name conventions of Rust types. With a unified `structx!{}`, the readers have to distinguish between values and types by parsing the inner of `structx!{}` themselves. 

On the other hand, distinguishing between expressions and patterns without `structxp!{}` seems to be easier because of the leading`match`, `if`, `let` keywords which appear before `structx!{}`.

**Comment by exellian** [comment]
Yeah I think leaving it as it is and just changing parsing behaviour is probably the best. After thinking again about solution 2. I came to the conclusion that this isn't even possible and the overhead of an additional macro structxp is not necessary.

**Comment by exellian** [comment]
So here it is #7 !
I added two major things:
- collection of anonymous structs in expressions
- Correct parsing of the inner part of all structx macros, so that really every macro call will trigger the collection of an anonymous struct
- completely removed all of the collection functions and replaced them with visit calls
