### ISSUE TITLE
Collection of anonymous structs inside other macros

### ISSUE THREAD

**Issue by exellian** [oooutlk/structx#8]
So currently the macro problem still exists. So if you write structx! inside another macro, the struct will not be collected and it will lead to an "type not found error". To reproduce it you just have to use the structx! {} macro alone, without accidentally triggering the collection with the use of a different Structx macro. Therefore the following program will not compile:

```rust 
fn main() {
    let test1 = Vec::from([structx! { lelele: "" }]); // Will not throw an error
    let test = vec![structx! { lelele1: 0 }]; // Will throw an error because the inner of other macros like vec![] is currently not analysed
}
```
If you trigger the collection of the struct with the use of another use of the structx macros then the program will still compile:
```rust
type Test = Structx! { // This will trigger the collection of the struct
    lelele1: usize
};

fn main() {
    let test = vec![structx! { lelele1: 0 }]; // This will not throw an error anymore 
}
```

The solution to the problem is actually not quite trivial, because the inner part of other macros can be arbitrary. So we don't even know if the inner part of other macros is valid rust code. 

One way of still supporting a lot of macros is trying to parse the inner part of other macros as Punctuated::<Expr, AnyToken>. So if the inner part of a macro is some type of list of expressions, then we can collect every occurrence of macros inside these expressions. The problem with this solution is that it could also lead to the collection of certain struct-types which will never be used, because we could accidentally succeed parsing the inner part of another macro which intended to use the text "structx! { ... }" in a different context.

A better solution but a solution which requires much more work would be to support certain macros by hand. In this type of scenario we know what a valid input to these macros is and we can parse accordingly. E.g: we could support parsing the inner part of vec![] macro and parse against Punctuated::<Expr, Token[,]> or a sequence consisting out of Expr Token[;] Expr.

**Comment by oooutlk** [comment]
It seems we reached the limitations of simulating a language feature. The collection of `structx!{}`/`Structx!{}` happens in an earlier stage before `vec![]` expansions. It’s a build script not a compiler and won’t expand arbitrary macros. Another failure scenario is missing the contents of `include!()`. Unless some method other than literal analysis via syn is discovered( if possible), I don’t think anonymous struct simulations will be perfect.

**Comment by oooutlk** [comment]
The structx 0.1.11 has been published to fix this issue.
